/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DEFAULT_NODE_LABEL_ATLAS_FONT_SIZE: typeof import('../../src/runtime/utils/node-label-atlas').DEFAULT_NODE_LABEL_ATLAS_FONT_SIZE
  const DEFAULT_NODE_LABEL_ATLAS_MAX_TEXTURE_SIZE: typeof import('../../src/runtime/utils/node-label-atlas').DEFAULT_NODE_LABEL_ATLAS_MAX_TEXTURE_SIZE
  const applyGraphDiff: typeof import('../../src/runtime/utils/apply-graph-diff').applyGraphDiff
  const applyNodeLabelAtlas: typeof import('../../src/runtime/utils/node-label-atlas').applyNodeLabelAtlas
  const composeStyles: typeof import('../../src/runtime/utils/compose-styles').composeStyles
  const createMinimapProjection: typeof import('../../src/runtime/utils/minimap-projection').createMinimapProjection
  const defineSigmaPrimitives: typeof import('../../src/runtime/utils/define-sigma-primitives').defineSigmaPrimitives
  const degreeToTier: typeof import('../../src/runtime/utils/graph-visual').degreeToTier
  const isLazySigmaPrimitives: typeof import('../../src/runtime/utils/define-sigma-primitives').isLazySigmaPrimitives
  const labelPlacements: typeof import('../../src/runtime/utils/graph-visual').labelPlacements
  const registerSigma: typeof import('../../src/runtime/composables/use-sigma').registerSigma
  const sdfPolygon: typeof import('../../src/runtime/utils/node-shape').sdfPolygon
  const sdfStar: typeof import('../../src/runtime/utils/node-shape').sdfStar
  const useSigma: typeof import('../../src/runtime/composables/use-sigma').useSigma
  const useSigmaById: typeof import('../../src/runtime/composables/use-sigma').useSigmaById
  const useSigmaCamera: typeof import('../../src/runtime/composables/use-sigma-camera').useSigmaCamera
  const useSigmaDrag: typeof import('../../src/runtime/composables/use-sigma-drag').useSigmaDrag
  const useSigmaEvents: typeof import('../../src/runtime/composables/use-sigma-events').useSigmaEvents
  const useSigmaExport: typeof import('../../src/runtime/composables/use-sigma-export').useSigmaExport
  const useSigmaFilter: typeof import('../../src/runtime/composables/use-sigma-filter').useSigmaFilter
  const useSigmaGraph: typeof import('../../src/runtime/composables/use-sigma-graph').useSigmaGraph
  const useSigmaIds: typeof import('../../src/runtime/composables/use-sigma').useSigmaIds
  const useSigmaLabelTiers: typeof import('../../src/runtime/composables/use-sigma-label-tiers').useSigmaLabelTiers
  const useSigmaLayout: typeof import('../../src/runtime/composables/use-sigma-layout').useSigmaLayout
  const useSigmaMetrics: typeof import('../../src/runtime/composables/use-sigma-metrics').useSigmaMetrics
  const useSigmaNeighborhood: typeof import('../../src/runtime/composables/use-sigma-neighborhood').useSigmaNeighborhood
  const useSigmaSearch: typeof import('../../src/runtime/composables/use-sigma-search').useSigmaSearch
  const useSigmaSelection: typeof import('../../src/runtime/composables/use-sigma-selection').useSigmaSelection
  const useSigmaSettings: typeof import('../../src/runtime/composables/use-sigma-settings').useSigmaSettings
  const useSigmaState: typeof import('../../src/runtime/composables/use-sigma-state').useSigmaState
  const watchNodeLabelAtlasOverflow: typeof import('../../src/runtime/utils/node-label-atlas').watchNodeLabelAtlasOverflow
}
// for type re-export
declare global {
  // @ts-ignore
  export type { SigmaFitInsets, SigmaFitOptions, UseSigmaCameraReturn } from '../../src/runtime/composables/use-sigma-camera'
  import('../../src/runtime/composables/use-sigma-camera')
  // @ts-ignore
  export type { UseSigmaDragOptions, UseSigmaDragReturn } from '../../src/runtime/composables/use-sigma-drag'
  import('../../src/runtime/composables/use-sigma-drag')
  // @ts-ignore
  export type { SigmaEventHandlers } from '../../src/runtime/composables/use-sigma-events'
  import('../../src/runtime/composables/use-sigma-events')
  // @ts-ignore
  export type { SigmaExportOptions, UseSigmaExportReturn } from '../../src/runtime/composables/use-sigma-export'
  import('../../src/runtime/composables/use-sigma-export')
  // @ts-ignore
  export type { SigmaNodePredicate, SigmaEdgePredicate, UseSigmaFilterOptions, UseSigmaFilterReturn } from '../../src/runtime/composables/use-sigma-filter'
  import('../../src/runtime/composables/use-sigma-filter')
  // @ts-ignore
  export type { UseSigmaGraphReturn } from '../../src/runtime/composables/use-sigma-graph'
  import('../../src/runtime/composables/use-sigma-graph')
  // @ts-ignore
  export type { SigmaLabelTierBreakpoint, UseSigmaLabelTiersOptions, UseSigmaLabelTiersReturn } from '../../src/runtime/composables/use-sigma-label-tiers'
  import('../../src/runtime/composables/use-sigma-label-tiers')
  // @ts-ignore
  export type { SigmaLayoutComponentOptions, UseSigmaLayoutOptions, UseSigmaLayoutReturn } from '../../src/runtime/composables/use-sigma-layout'
  import('../../src/runtime/composables/use-sigma-layout')
  // @ts-ignore
  export type { SigmaCentralityKind, UseSigmaMetricsReturn } from '../../src/runtime/composables/use-sigma-metrics'
  import('../../src/runtime/composables/use-sigma-metrics')
  // @ts-ignore
  export type { UseSigmaNeighborhoodOptions, UseSigmaNeighborhoodReturn } from '../../src/runtime/composables/use-sigma-neighborhood'
  import('../../src/runtime/composables/use-sigma-neighborhood')
  // @ts-ignore
  export type { SigmaSearchResult, UseSigmaSearchOptions, UseSigmaSearchReturn } from '../../src/runtime/composables/use-sigma-search'
  import('../../src/runtime/composables/use-sigma-search')
  // @ts-ignore
  export type { UseSigmaSelectionOptions, UseSigmaSelectionReturn } from '../../src/runtime/composables/use-sigma-selection'
  import('../../src/runtime/composables/use-sigma-selection')
  // @ts-ignore
  export type { UseSigmaStateReturn } from '../../src/runtime/composables/use-sigma-state'
  import('../../src/runtime/composables/use-sigma-state')
  // @ts-ignore
  export type { ApplyGraphDiffOptions } from '../../src/runtime/utils/apply-graph-diff'
  import('../../src/runtime/utils/apply-graph-diff')
  // @ts-ignore
  export type { LabelPlacementsOptions, DegreeToTierOptions } from '../../src/runtime/utils/graph-visual'
  import('../../src/runtime/utils/graph-visual')
  // @ts-ignore
  export type { SigmaMatrixUtils, MinimapProjection } from '../../src/runtime/utils/minimap-projection'
  import('../../src/runtime/utils/minimap-projection')
  // @ts-ignore
  export type { SigmaLabelAtlasOptions, NodeLabelAtlasFont } from '../../src/runtime/utils/node-label-atlas'
  import('../../src/runtime/utils/node-label-atlas')
  // @ts-ignore
  export type { SdfPolygonOptions, SdfStarOptions } from '../../src/runtime/utils/node-shape'
  import('../../src/runtime/utils/node-shape')
}
