/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    SigmaControls: typeof import('./../../src/runtime/components/controls/Controls.vue')['default']
    SigmaFullscreenControl: typeof import('./../../src/runtime/components/controls/FullscreenControl.vue')['default']
    SigmaGraph: typeof import('./../../src/runtime/components/Graph.vue')['default']
    SigmaZoomControl: typeof import('./../../src/runtime/components/controls/ZoomControl.vue')['default']
  }
}
